services:
  - type: web
    name: streamflix-web
    env: node
    plan: free
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: JWT_SECRET
        generateValue: true
      - key: ADMIN_EMAIL
        value: admin@streamflix.com
      - key: ADMIN_PASSWORD
        value: Admin@12345
